version: '3.8'

services:
  website:
    container_name: website
    build:
      context: ./website
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./website/app:/var/www/html:z
    ports:
      - "8000:80"
    networks:
      - appnetwork
    depends_on:
      - dbwebsite
      - user_soap_api

  dbwebsite:
    image: mariadb:latest
    container_name: dbwebsite
    restart: unless-stopped
    environment:
      - MARIADB_DATABASE=websitedatabase
      - MARIADB_USER=user
      - MARIADB_PASSWORD=password
      - MARIADB_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - ./website/db_data:/var/lib/mysql:z
    networks:
      - appnetwork

  user_soap_api:
    container_name: user_soap_api
    build:
      context: services/ProfileAPISOAP/UserProfileSoap
      dockerfile: ./Dockerfile
    restart: unless-stopped
    ports:
      - "8002:5109"
    networks:
      - appnetwork
    depends_on:
      - db_user_profile

  db_user_profile:
    image: postgres:14
    container_name: db_user_profile
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=user_profile_database
    ports:
      - "5433:5432"
    volumes:
      - ./services/userProfileAPI/db_data:/var/lib/postgresql/data:Z
    networks:
      - appnetwork

  restapi:
    container_name: restapi
    build:
      context: services/jsonRestApi
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - appnetwork

  adminer:
    image: adminer:4.8.1-standalone
    restart: unless-stopped
    ports:
      - 8080:8080
    networks:
      - appnetwork

networks:
  appnetwork:
    driver: bridge